// 食材對照：中文關鍵字 → 約旦阿拉伯語（ar）、發音（p）、英文（en）
// 比對時取最長的關鍵字；發音用簡單拼音，ʾ = 喉音停頓，kh = 喉嚨擦音，ḥ = 深 h
window.ING_DICT = [
  ["雞胸","صدر دجاج","ṣadr djāj","chicken breast"],["雞腿","فخذ دجاج","fakhd djāj","chicken thigh"],["雞翅","جوانح دجاج","jawāneḥ djāj","chicken wings"],
  ["雞絞肉","دجاج مفروم","djāj mafrūm","minced chicken"],["全雞","جاجة كاملة","jāje kāmle","whole chicken"],["雞肉","دجاج","djāj","chicken"],["雞","دجاج","djāj","chicken"],
  ["雞胗","قوانص دجاج","qawāneṣ djāj","chicken gizzards"],["雞油","دهن دجاج","dihn djāj","chicken fat"],["雞骨","عظم دجاج","ʿaḍm djāj","chicken bones"],
  ["牛絞肉","لحمة عجل مفرومة","laḥmet ʿijil mafrūme","minced beef"],["牛腩","لحمة صدر عجل","laḥmet ṣadr ʿijil","beef brisket"],["牛腱","موزات عجل","mōzāt ʿijil","beef shank"],
  ["牛肋","ضلوع عجل","ḍulūʿ ʿijil","beef ribs"],["肋眼","ريب آي","rib eye","ribeye"],["牛里肌","فيليه عجل","filēh ʿijil","beef tenderloin"],["牛尾","ذنب عجل","dhanab ʿijil","oxtail"],
  ["牛筋","عصب عجل","ʿaṣab ʿijil","beef tendon"],["牛骨","عظم عجل","ʿaḍm ʿijil","beef bones"],["牛肉","لحمة عجل","laḥmet ʿijil","beef"],["牛","لحمة عجل","laḥmet ʿijil","beef"],
  ["羊絞肉","لحمة خروف مفرومة","laḥmet kharūf mafrūme","minced lamb"],["羊排","ريش خروف","rīsh kharūf","lamb chops"],["羊肉","لحمة خروف","laḥmet kharūf","lamb"],["羊","لحمة خروف","laḥmet kharūf","lamb"],
  ["肥肉","دهن","dihn","fat"],["豬","لحم خنزير","laḥm khanzīr","pork（只有少數基督徒商店）"],
  ["鮭魚","سلمون","salamōn","salmon"],["鱸魚","قاروص","qārūṣ","sea bass"],["章魚","أخطبوط","ukhṭubūṭ","octopus"],["蝦","جمبري","jambari","shrimp"],["魚片","فيليه سمك","filēh samak","fish fillet"],["魚","سمك","samak","fish"],
  ["鹹蛋黃","صفار بيض مملح","ṣafār bēḍ mumallaḥ","salted egg yolk"],["蛋黃","صفار بيض","ṣafār bēḍ","egg yolk"],["蛋白","بياض البيض","bayāḍ il-bēḍ","egg white"],["雞蛋","بيض","bēḍ","eggs"],["蛋","بيض","bēḍ","eggs"],
  ["豆腐","توفو","tōfu","tofu"],["豆乾","توفو مجفف","tōfu mjaffaf","dried tofu"],
  ["紫洋蔥","بصل أحمر","baṣal aḥmar","red onion"],["紅蔥頭","بصل صغير / شالوت","shalōt","shallot"],["洋蔥","بصل","baṣal","onion"],["青蔥","بصل أخضر","baṣal akhḍar","green onion"],["蔥","بصل أخضر","baṣal akhḍar","green onion"],
  ["蒜苗","ثوم أخضر","thūm akhḍar","green garlic"],["蒜","ثوم","thūm","garlic"],["薑","زنجبيل","zanjabīl","ginger"],["韭菜","كراث","kurrāth","chives / leek"],
  ["香菜","كزبرة خضرا","kuzbara khaḍra","coriander"],["巴西里","بقدونس","baʾdūnes","parsley"],["九層塔","ريحان","rēḥān","basil"],["羅勒","ريحان","rēḥān","basil"],["薄荷","نعنع","naʿnaʿ","mint"],
  ["辣椒粉","فلفل أحمر مطحون","filfil aḥmar maṭḥūn","chili powder"],["青椒","فلفل حلو أخضر","filfil ḥilu akhḍar","green bell pepper"],["甜椒","فلفل حلو","filfil ḥilu","bell pepper"],["辣椒","فلفل حار","filfil ḥārr","chili"],
  ["小番茄","بندورة شيري","bandōra sheri","cherry tomato"],["日曬番茄","بندورة مجففة","bandōra mjaffafe","sun-dried tomato"],["番茄泥","رب بندورة","rubb bandōra","tomato paste"],["番茄","بندورة","bandōra","tomato"],["蕃茄","بندورة","bandōra","tomato"],
  ["馬鈴薯","بطاطا","baṭāṭa","potato"],["土豆","بطاطا","baṭāṭa","potato"],["地瓜","بطاطا حلوة","baṭāṭa ḥilwe","sweet potato"],["紅薯","بطاطا حلوة","baṭāṭa ḥilwe","sweet potato"],["番薯","بطاطا حلوة","baṭāṭa ḥilwe","sweet potato"],
  ["紅蘿蔔","جزر","jazar","carrot"],["胡蘿蔔","جزر","jazar","carrot"],["白蘿蔔","فجل أبيض","fijil abyaḍ","daikon"],["蘿蔔","فجل","fijil","radish"],
  ["大白菜","ملفوف صيني","malfūf ṣīni","napa cabbage"],["高麗菜","ملفوف","malfūf","cabbage"],["小白菜","بوك تشوي","bok choy","bok choy"],["花椰菜","زهرة","zahra","cauliflower"],["菠菜","سبانخ","sabānikh","spinach"],
  ["小黃瓜","خيار","khyār","cucumber"],["節瓜","كوسا","kūsa","zucchini"],["櫛瓜","كوسا","kūsa","zucchini"],["茄子","بتنجان","batinjān","eggplant"],["苦瓜","قرع مر","ʾaraʿ murr","bitter melon"],["南瓜","قرع","ʾaraʿ","pumpkin"],
  ["玉米","ذرة","dhura","corn"],["香菇","فطر شيتاكي","fuṭr shītāki","shiitake"],["蘑菇","فطر / مشروم","mashrūm","mushroom"],["豆芽","براعم فول الصويا","barāʿem","bean sprouts"],["四季豆","فاصوليا خضرا","fāṣūlya khaḍra","green beans"],
  ["鷹嘴豆","حمص","ḥummuṣ","chickpeas"],["紅豆","فاصوليا حمرا صغيرة (أزوكي)","azuki","adzuki beans"],["綠豆","عدس ماش","ʿadas māsh","mung beans"],["栗子","كستنا","kastana","chestnuts"],["蓮藕","جذر اللوتس","jidhr il-lōtus","lotus root"],
  ["芹菜","كرفس","karafs","celery"],["山藥","يام","yām","yam"],["甜菜根","شمندر","shamandar","beetroot"],["空心菜","سبانخ مائية","sabānikh māʾiyye","water spinach"],
  ["檸檬汁","عصير ليمون","ʿaṣīr lēmōn","lemon juice"],["檸檬","ليمون","lēmōn","lemon"],["柳橙","برتقال","burtʾān","orange"],["橘子","يوسفي","yūsufi","mandarin"],["芒果","مانجا","manga","mango"],
  ["李子","خوخ","khōkh","plum（約旦叫 khōkh）"],["桃子","دراق","durrāʾ","peach"],["椰棗","تمر","tamr","dates"],["葡萄乾","زبيب","zbīb","raisins"],["核桃","جوز","jōz","walnuts"],["花生","فستق عبيد","fustuʾ ʿabīd","peanuts"],
  ["黑芝麻","سمسم أسود","simsim aswad","black sesame（不是 حبة البركة）"],["芝麻","سمسم","simsim","sesame"],["蔓越莓","توت بري","tūt barri","cranberry"],
  ["糯米","رز دبق","ruzz dabiq","glutinous rice"],["白米","رز أبيض","ruzz abyaḍ","white rice"],["米","رز","ruzz","rice"],["藜麥","كينوا","kīnwa","quinoa"],["燕麥","شوفان","shūfān","oats"],
  ["全麥麵粉","طحين أسمر","ṭḥīn asmar","whole wheat flour"],["高筋麵粉","طحين خبز","ṭḥīn khubz","bread flour"],["強力麵粉","طحين خبز","ṭḥīn khubz","bread flour"],["裸麥","طحين جاودار","ṭḥīn jāwdār","rye flour"],["麵粉","طحين","ṭḥīn","flour"],
  ["太白粉","نشا","nasha","starch"],["玉米粉","نشا ذرة","nashat dhura","cornstarch"],["地瓜粉","نشا بطاطا حلوة","nasha","sweet potato starch"],["麵包粉","بقسماط","baʾsamāṭ","breadcrumbs"],
  ["冰糖","سكر نبات","sukkar nabāt","rock sugar"],["砂糖","سكر","sukkar","sugar"],["糖粉","سكر بودرة","sukkar bōdra","powdered sugar"],["黑糖","سكر بني","sukkar bunni","brown sugar"],["糖","سكر","sukkar","sugar"],
  ["鹽","ملح","milḥ","salt"],["白胡椒","فلفل أبيض","filfil abyaḍ","white pepper"],["黑胡椒","فلفل أسود","filfil aswad","black pepper"],["胡椒","فلفل","filfil","pepper"],
  ["孜然","كمون","kammūn","cumin"],["小茴香","شومر (بذور)","shūmar","fennel seeds"],["八角","يانسون نجمي","yansūn najmi","star anise"],["肉桂","قرفة","ʾirfe","cinnamon"],["荳蔻","هيل","hēl","cardamom"],["豆蔻","هيل","hēl","cardamom"],
  ["月桂葉","ورق غار","waraq ghār","bay leaves"],["丁香","قرنفل","ʾurunful","cloves"],["薑黃","كركم","kurkum","turmeric"],["咖哩","كاري","kāri","curry"],["五香粉","بهارات صينية خمسة","bahārāt ṣīniyye","five-spice"],
  ["花椒","فلفل سيشوان","filfil sichuan","Sichuan pepper"],["甘草","عرق سوس","ʿirʾ sūs","licorice"],["百里香","زعتر","zaʿtar","thyme"],["奧勒岡","أوريغانو","origano","oregano"],
  ["醬油膏","صويا صوص كثيفة","ṣōya ṣōṣ","thick soy sauce"],["醬油","صويا صوص","ṣōya ṣōṣ","soy sauce"],["生抽","صويا صوص","ṣōya ṣōṣ","soy sauce"],["蠔油","صلصة المحار","ṣalṣat il-maḥār","oyster sauce"],["魚露","صلصة السمك","ṣalṣat is-samak","fish sauce"],
  ["烏醋","خل أسود","khall aswad","black vinegar"],["白醋","خل أبيض","khall abyaḍ","white vinegar"],["巴薩米克","خل بلسميك","khall balsamik","balsamic"],["醋","خل","khall","vinegar"],
  ["米酒","نبيذ أرز (كحول)","—","rice wine（含酒精）"],["味醂","ميرين","mirin","mirin"],["味琳","ميرين","mirin","mirin"],
  ["香油","زيت سمسم","zēt simsim","sesame oil"],["麻油","زيت سمسم","zēt simsim","sesame oil"],["橄欖油","زيت زيتون","zēt zētūn","olive oil"],["植物油","زيت نباتي","zēt nabāti","vegetable oil"],["油","زيت","zēt","oil"],
  ["奶油","زبدة","zibde","butter"],["Ghee","سمنة","samne","ghee"],["牛奶","حليب","ḥalīb","milk"],["鮮奶","حليب","ḥalīb","milk"],["煉乳","حليب مكثف محلى","ḥalīb mukaththaf","condensed milk"],["淡奶","حليب مبخر","ḥalīb mubakhkhar","evaporated milk"],
  ["鮮奶油","كريمة","krēma","cream"],["優格","لبن","laban","yogurt（約旦叫 laban）"],["Labneh","لبنة","labne","labneh"],["奶油乳酪","جبنة كريمية","jibne krēmiyye","cream cheese"],["Feta","جبنة فيتا","jibne fēta","feta"],["起司","جبنة","jibne","cheese"],
  ["蜂蜜","عسل","ʿasal","honey"],["紅茶","شاي أحمر","shāy aḥmar","black tea"],["茶葉","شاي","shāy","tea"],["咖啡","قهوة","ʾahwe","coffee"],
  ["美乃滋","مايونيز","mayonēz","mayonnaise"],["番茄醬","كاتشب","kātshab","ketchup"],["義大利麵","معكرونة","maʿkarōna","pasta"],["麵條","شعيرية / نودلز","nūdelz","noodles"],
  ["酵母","خميرة","khamīre","yeast"],["泡打粉","بيكنج باودر","beking pawder","baking powder"],["小蘇打","كربونة","karbōne","baking soda"],["檸檬酸","ملح ليمون","milḥ lēmōn","citric acid"],
  ["高湯","مرقة","maraʾa","stock"],["雞湯塊","مكعبات مرقة دجاج","mukaʿʿabāt maraʾa","chicken stock cube"],["水","مي","mayy","water"],["冰塊","تلج","talj","ice"]
];
// 約旦不好買時的替代（整理自 Benson 問過 Gemini 的內容；可自行修改）
window.SUBS = {
  "油蔥酥":"中東炸洋蔥（超市有賣 بصل مقلي），或用小紫洋蔥自己炸",
  "紅蔥頭":"小顆紫洋蔥",
  "油麵":"義大利麵＋少量小蘇打一起煮，做出鹼水麵口感",
  "蛤蜊":"干貝粉、少量魚露，或冷凍海鮮",
  "味醂":"糖＋少量白醋＋水（或蜂蜜）",
  "味琳":"糖＋少量白醋＋水（或蜂蜜）",
  "昆布":"雞高湯＋幾滴魚露",
  "米酒":"約旦不好買、也不適合給穆斯林朋友：可用薑片去腥，或少量白醋＋水",
  "豬":"牛肉或雞肉（豬肉只有少數基督徒商店有）",
  "臘肉":"煙燻牛肉（Yaser Mall 找得到）",
  "地瓜粉":"太白粉或玉米粉，加一點麵包粉增加酥脆",
  "黑胡椒醬":"自製：粗黑胡椒＋番茄醬＋醬油＋一小塊奶油",
  "糯米粉":"米粉或細粒小麥粉（semolina）",
  "白蘿蔔":"熬湯可用蘋果代替，增加甜味",
  "柴魚":"干貝粉或魚露（過敏或抗生素期間請少用）",
  "香蘭":"可省略，或用極少量香草精",
  "鴨":"用烤雞做出烤鴨風味",
  "鹹蛋":"亞洲超市的冷凍鹹蛋黃，或自己醃",
  "黑芝麻":"注意：約旦常見的黑色小籽是 حبة البركة（黑種草籽），不是黑芝麻",
  "甜酒麴":"網路或亞洲超市；沒有時可試果酒酵母",
  "沙茶":"亞洲超市（安曼有少數幾家）",
  "豆瓣醬":"亞洲超市；急用時辣椒醬＋少量味噌或醬油",
  "Buttermilk":"約旦超市的 Buttermilk 其實是發酵乳飲，可用牛奶＋少量檸檬汁代替"
};

// 英文版的約旦替代建議（鍵跟 SUBS 一樣，用中文比對材料名稱）
window.SUBS_EN = {
  "油蔥酥": "Middle Eastern fried onions (sold in supermarkets as بصل مقلي), or fry small red onions yourself",
  "紅蔥頭": "Small red onions",
  "油麵": "Spaghetti boiled with a pinch of baking soda for an alkaline-noodle bite",
  "蛤蜊": "Dried scallop powder, a little fish sauce, or frozen seafood",
  "味醂": "Sugar + a little white vinegar + water (or honey)",
  "味琳": "Sugar + a little white vinegar + water (or honey)",
  "昆布": "Chicken stock + a few drops of fish sauce",
  "米酒": "Hard to find in Jordan and not suitable for Muslim friends: use ginger slices to remove gaminess, or a little white vinegar + water",
  "豬": "Beef or chicken (pork is only sold in a few Christian-run shops)",
  "臘肉": "Smoked beef (available at Yaser Mall)",
  "地瓜粉": "Potato starch or cornstarch, plus a little breadcrumb for extra crunch",
  "黑胡椒醬": "Homemade: coarse black pepper + ketchup + soy sauce + a small knob of butter",
  "糯米粉": "Rice flour or fine semolina",
  "白蘿蔔": "For soups, an apple adds similar sweetness",
  "柴魚": "Dried scallop powder or fish sauce (use less if allergic or on antibiotics)",
  "香蘭": "Skip it, or use a tiny drop of vanilla extract",
  "鴨": "Use roast chicken for a roast-duck flavor",
  "鹹蛋": "Frozen salted egg yolks from Asian grocers, or cure your own",
  "黑芝麻": "Note: the small black seeds common in Jordan are حبة البركة (nigella seeds), not black sesame",
  "甜酒麴": "Online or at Asian grocers; if unavailable, try fruit-wine yeast",
  "沙茶": "Asian grocers (a few in Amman)",
  "豆瓣醬": "Asian grocers; in a pinch, chili sauce + a little miso or soy sauce",
  "Buttermilk": "Jordanian supermarket \"buttermilk\" is a fermented milk drink; use milk + a little lemon juice instead"
};
